### PR TITLE
Fixed for linux and overlay issues

### PR DESCRIPTION
**Pull request by Black4Blade**
*Fix for issue #113
*Added new text tweak on request (+8)
*Fixed overlay missing links for controller config and force close (we may want to make a icon for it, and place it somewhere else for better looks)

If anyone can just test and make sure it's not creating an issue before merging just to be on the safe side that be good

### CODE REVIEW

**Comment by halbrd** [comment]
Just tried it out in Windows 7 and I don't see any issues. Are there any UI elements in particular that I should check?

**Comment by Black4Blade** [comment]
The overlay if not on Linux

**Comment by halbrd** [comment]
image
Looks good to me.

**Comment by Black4Blade** [comment]
Ok then guess will do it... when i get back on PC

**Pull request merged**
