### PR TITLE
Fixed EOL message that was underhanded for XP

### PR DESCRIPTION
**Pull request by Black4Blade**
Fixed an end of life message for XP users that was unhandled before (also removed some extra fixes that did not seem to be known if they fix the issue there where for XD, so it's only the EOL message fix really)

### CODE REVIEW

**Comment by Black4Blade** [comment]
If anyone wants to test this out before I confirm a merge? done one test with the one that reported it, but I don't have an XP machine to test it on to see if its fixed correctly or not

**Comment by halbrd** [comment]
I'll see if I can test it out in an XP virtual machine over the weekend.

I assume there's little to no chance of this breaking anything for other platforms?

**Comment by halbrd** [comment]
Any chance we can get a screencap of the fixed dialog box for the sake of documentation?

Regardless, I think this is fine to merge.

**Comment by Black4Blade** [comment]
> Any chance we can get a screencap of the fixed dialog box for the sake of documentation?
> 
> Regardless, I think this is fine to merge.

You got the Virtual Machine with XP no?
I can try to install one, just need the time to get around to it really XD
I cant see it on what I got right now, so be hard to take a screenshot for it

**Comment by halbrd** [comment]
I was hoping I had an XP disk image but I don't.

I figure that since:

- it worked for the reporter
- the majority of users should never see the window (and honestly, if you're still running XP, a broken dialogue box is the least of your worries)
- the changes don't seem to touch anything else, so there's very little chance of unrelated breakages

it's probably not worth the effort of actually setting up a VM to verify it further.

Btw, @Black4Blade , you're a legend for keeping Pixelvision going. I hope to be contributing more than just PR comments in the future!

**Comment by somini** [comment]
> Btw, @Black4Blade , you're a legend for keeping Pixelvision going. I hope to be contributing more than just PR comments in the future!

Amen to that.

**Pull request merged**
