### PR TITLE
Minor Fixes

### PR DESCRIPTION
**Pull request by CaptainMagma**
The download page border had an extra outer dark gray border on the left, bottom, and right side of the panel. This has been fixed to match the borders of the other panels.

Converted status icon images from .png to .tga and edited the friendpanel.layout so those who name there skin folder anything other than "PixelVision" can see the status icons.

The hint text "Search" in the search bar was not italic to match the rest. This has now been fixed.

Removed the version number of the skin.

Updated for latest Steam beta update to add a couple new broadcast viewing features.

### CODE REVIEW

**Comment by somini** [comment]
There's an extra version number in the about dialog.
I hope you are updating them in a somewhat automatic way, it would be a chore otherwise. With the git repo, the version number only really matters for the proper versions anyway.
Maybe put "git version" or something and change only for proper releases.

**Comment by CaptainMagma** [comment]
I actually just wanted to remove the version numbers all together. I didn't understand the point of them being there after putting the skin on GitHub anyways. Think that would be a better idea?

**Comment by somini** [comment]
`git grep` to the rescue (again). I found 2 extra mentions of Pixelvision folder name and removed them.

**Comment by somini** [comment]
Yeah, the version numbers are meaningless now. Maybe open a thread on Steam forums?

I'll have to go now, I'll merge this PR tomorrow.

**Comment by CaptainMagma** [comment]
I'll remove the version numbers and add the removed mentions of the PixelVision folder name to this merge as well while I'm at it.

**Comment by somini** [comment]
I'm merging this.

**Pull request merged**
