### PR TITLE
Added: Windows installer

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
image

**Comment by dvdvideo1234** [comment]
Is it OK if the fonts are added inside the repo. I mean the fonts link will not be forever...

**Comment by halbrd** [comment]
Hey @dvdvideo1234 , thanks for offering your install script for Pixelvision. However the purpose of this repo is to house the source files of the skin itself - we don't keep computer code like scripts in here. This is a bit of software that's best as a standalone - maybe with a few tweaks it could be a generic Steam skin installer. But it doesn't belong in with the skin itself.

**Comment by dvdvideo1234** [comment]
Oke.. So if anyone wants to use it you can get it from y my repo. Made it universal. Drag-drop the pixelvision folder onto the `*.bat` file to install it in the proper folder pointed by the windows registry.

https://github.com/dvdvideo1234/WindowsBatches/blob/master/SteamGames/SkinInstaller/SkinInstall.bat

**Pull request closed without merging**
