### PR TITLE
Re-Align Family View Button

### PR DESCRIPTION
**Pull request by CaptainMagma**
Everything works on my end after testing the fix. Let me know if anything else needs to be fixed (please test with PixelVision default settings).

### CODE REVIEW

**Comment by somini** [comment]
Hmm, I still got some issues. Tested by checking out the `pull/51` branch.
Family View off
screenshot from 2015-09-22 21 51 58
Family View on
screenshot from 2015-09-22 21 51 43
I'd use `margin-right: 60` for a little extra headroom, but where is the other misalignment coming from?

**Comment by CaptainMagma** [comment]
You tested on PixelVision default settings? That doesn't look like the default font.

**Comment by somini** [comment]
It's the Linux client font bug then.

If you can send me a screenshot of the Windows version I'll merge this.

**Comment by CaptainMagma** [comment]
I don't know if the font is to blame or not. I was just unsure as to whether or not you were on default settings since the font was different. I'll have to look into this some more later on this week. There's no rush. It's a small bug and I don't have much free time right now.

**Comment by somini** [comment]
Very well, take your time. It's a cosmetic bug anyway.

**Comment by CaptainMagma** [comment]
One last thing: could you tell me what features you have enabled/disabled for family view?

**Comment by somini** [comment]
I left all the options ticked off, it's the least amount of access possible.

**Comment by CaptainMagma** [comment]
Yea, after doing that, I now have the same problem you are having. Thanks for the feedback. I'll be looking into this later in the week.

**Comment by CaptainMagma** [comment]
This last edit should fix the alignment issue with the account url when it's disabled. As for the margin of the Family View icon, I chose to leave it at 50 because it was already farther to the left than it was before I submitted this pull request. I think the font bug that you have is causing the Family View icon to align too close.

**Comment by somini** [comment]
Yup, it's fixed now, thanks for the quick response.
I think I'll merge this so that it's easier to test.

**Pull request merged**
