### PR TITLE
Add more menu items

### PR DESCRIPTION
**Pull request by Bluscream**
Like docs and gameserver/apikey management

### CODE REVIEW

**Comment by halbrd** [comment]
Looks good to me :+1:  Thanks for your work!

**Comment by Black4Blade** [comment]
Looks really good to me, Thanks for the work, looks good

**Review by Black4Blade — COMMENTED** [review]
Great work, looks good, adds great function to the skin

**Comment by Bluscream** [comment]
woah, hold on. It wasn't supposed to be merged, at least not without a proper discussion. The new menu items should be merged into one so it doesn't take so much space for "normal" users.

**Comment by Black4Blade** [comment]
I cant see it really harm much
But guess you right on that, can change it maybe to only show when someone set up on developer mode when the console shows up

Don't think it will harm much whatever the case is

**Pull request merged**
