### PR TITLE
Fixed the skin for the new Chat UI

### PR DESCRIPTION
**Pull request by Black4Blade**
Was thinking to offer this to the main branch for Pixelvision2 now that the ChatUI is out of beta

### CODE REVIEW

**Comment by halbrd** [comment]
Just tried it out, looks really good. Only question - the menu in the screenshot doesn't collapse unless I click the button (where the cursor is) - expected behavior would probably be for the menu to collapse if you click outside of it. 
image

Edit: just tested it without a skin - same behavior, so it's not a skin-specific thing. I say let's merge. Thanks @Black4Blade for the quick PR!

**Comment by Black4Blade** [comment]
Hey gladly, working on a few more things to try to improve it a little more with some issues that where found
Will it be possible to announce in the group for users to be informed there is a newer version out XD

Also I am looking into seeing if there is a way to stop that menu thing from happening even that its happening with the default

Edit2: can you merage it? or your not able to do it? I am trying ot contact the guys with the group power to help spread there is a fix

**Comment by halbrd** [comment]
I have no power over the Steam group or this repo. I just checked here for any PRs that had an updated version. @somini

**Comment by Black4Blade** [comment]
I see, anyway thanks
Guess all the guys are busy, not sure if I should start a new group or something, honestly don't want to do it, I just patched it they did all the work after the original guy did all the work XD

**Comment by halbrd** [comment]
I wouldn't recommend making a new group. It'd be very unlikely to get any exposure. Best we can do for now is try to spread the word in the existing group and hope the repo admin(s) show up at some point. 

Edit: also consider making a post on /r/Steam.

**Comment by Black4Blade** [comment]
@halbrd
I do agree problem is now when I fix or update people need to look at the forums to find out about it
I may do that, its just I am not much of a reddit user 😅
So need to just view the rules and that
Also I do have a little issue now it seems in the settings that needs solving yet

**Comment by somini** [comment]
Hi,

I'm the owner of the repo.

I have been meaning to test this PR, but I'm in the middle of moving to
a different house, I'm still waiting for the Internet installation.
I will try to get this done this weekend.
Please ping me here if I forget.

I can give you both access to Github and the Steam group, as soon as I
can get real life sorted out. :D

**Comment by mr-late** [comment]
Life has been a pain lately for me too, specifically work. Haven't had the energy or interest to work on the skin since it works fine enough for me.

I checked the pull request and tested out the skin with the patches in. Everything look solid, so I'll merge this PR, there are still some outstanding issues in the settings menu that I'll begin working on.

**Comment by Black4Blade** [comment]
Thanks mate planing to do the same
And thanks for all your work

**Comment by halbrd** [comment]
Hey, just wanted to say thanks to you all for the work on Pixelvision. I'm happy to help out with management/development if some of the existing team wants to take a step back. I'm a competent coder and I want to see Pixelvision continue to thrive into the future 😄

**Comment by mr-late** [comment]
Helping out in the GitHub repo is the best course of action. Since somini controls the repo for the most part, I'll let him decide what the best course of action is regarding access to the repo itself.

**Comment by Black4Blade** [comment]
@somini Taken me a while to notice you reply XD
Anyway, good on you hope the new house is nice 😄 
And thanks anyway if you guys are around no real need to give opening for the repo except if you prefer not to look it over, I am somewhat new to skinning I mostly play around with it, but if help is needed il be glad to give it
I was mostly assuming you guys were just too busy to be able to do any work on it

Any case thanks

**Comment by somini** [comment]
Thanks for the kind words.

> I was mostly assuming you guys were just too busy to be able to do any work on it

That's the big reason, at least for me.

I just gave access to repo @halbrd and @Black4Blade . You can now merge PR and push to the repo (once you accept it). I can lurk about here, but you can now act on issues if I or @mr-late go into radio silence for a while.

**Pull request merged**
