### PR TITLE
Added console to view menu

### PR DESCRIPTION
**Pull request by Bluscream**
Are there more tweaks like that one? I would love to have a "Dev Mode" with all hidden tweaks enabled :)

### CODE REVIEW

**Comment by somini** [comment]
Who knows, only Valve employees. :)
There's this:
https://developer.valvesoftware.com/wiki/Steam://
Which is pretty complete.

**Comment by somini** [comment]
Well, this works even if you don't run Steam as Dev Mode or something, so I'm merging this.
Thanks for the contribution!

**Comment by joedf** [comment]
Very cool! :+1:

**Comment by Bluscream** [comment]
Thanks @somini :+1:

**Comment by somini** [comment]
Hmm, it should be. I think it involves `#var` or something similar.

**Pull request merged**
