### PR TITLE
Steam Beta Library

### PR DESCRIPTION
**Pull request by julliansl**
Implemented a working solution for the new Steam Beta Library. not sure if there's anything else missing needed to be added, just worked towards having the new library get displayed.

Here are screenshots of what's in this PR: https://imgur.com/a/3xUcbTp

Also I believe I pulled some of @Black4Blade 's work since I forked from his repo, not sure what was included

This PR also takes into giving a solution for issue #119.

### CODE REVIEW

**Comment by Bluscream** [comment]
Thanks

**Comment by halbrd** [comment]
I've tested it on Windows 10 and it looks great, but I'm getting a horizontal line near the top of the library interface on Linux (Manjaro 18.1.0, KDE Plasma 5.16.4, using this commit https://github.com/JSyLucero/Pixelvision2/tree/05712d8168216b9b78a1edd85e065d4946e028fc)
image

Thanks for the PR!

**Comment by JSyLucero** [comment]
> I've tested it on Windows 10 and it looks great, but I'm getting a horizontal line near the top of the library interface on Linux (Manjaro 18.1.0, KDE Plasma 5.16.4, using this commit https://github.com/JSyLucero/Pixelvision2/tree/05712d8168216b9b78a1edd85e065d4946e028fc)
> image
> 
> Thanks for the PR!

I'll try to see what I can do about that, although anyone else can pitch in a fix for it before me.

**Comment by julliansl** [comment]
> I've tested it on Windows 10 and it looks great, but I'm getting a horizontal line near the top of the library interface on Linux (Manjaro 18.1.0, KDE Plasma 5.16.4, using this commit https://github.com/JSyLucero/Pixelvision2/tree/05712d8168216b9b78a1edd85e065d4946e028fc)
> image
> 
> Thanks for the PR!

@halbrd I'll try to see what I can do about that, although anyone else can attempt to pitch in a fix for it too

**Comment by julliansl** [comment]
I've put in a fix for the overlapped border issue @halbrd, it should be gone now.

**Comment by halbrd** [comment]
It looks great! And you fixed the icon alignment! 😍
image

Thanks for your work! I'm happy for this to be merged when you're done working on it.

**Comment by julliansl** [comment]
> It looks great! And you fixed the icon alignment! 😍
> image
> 
> Thanks for your work! I'm happy for this to be merged when you're done working on it.

Glad to hear that! I felt quite in the mood to test the waters with updating a Steam skin for once and PixelVision is a skin I don't want to part with so I decided to use this as a chance xD. I'm glad its turned out pretty well so far, I haven't any ideas of what else I would need to do though, I'll let you know whenever I'm finished @halbrd.

**Comment by halbrd** [comment]
@JSyLucero where did you learn to edit Steam skins? I'm a programmer but I have no knowledge of how Steam skins work and there doesn't seem to be much clear documentation.

**Comment by julliansl** [comment]
@halbrd tbh, I dabble quite often in CSS on front-end Web Dev, so the logic behind skins and the values in them remind me of it. A lot of my learning comes from inspection with trial and error. Because of how I'm kind of blindly learning by doing constant change and tests, I'm trying my best to change things slowly to find out how it exchanges visually, and honestly.... having to restart Steam every time makes this a time consuming experience xD...

Also, documentation really is scarce and it kind of hurts to be honest, especially since I only just started trying this out.

Edit: I just found out the page to really learning how to get control names, etc and what each attribute/property does in Steam skins, here's the page, apparently its called **[VGUI Editing](https://developer.valvesoftware.com/wiki/VGUI_Editing)**

**Review by GiraffeCubed — APPROVED** [review]

**Pull request merged**
