### PR TITLE
Fix for some issues

### PR DESCRIPTION
**Pull request by Black4Blade**
*Fixed issue with the unhandled button for unpair and pair in the settings sub steaming file
*I think the others were already submitted before so not sure why they show up here

anyhow older fixs:
*Added a missing placing command for Linux potron button
*Added a huge font option for the settings
*Fixed overlay buttons for qruite game and controller settings

### CODE REVIEW

**Comment by Black4Blade** [comment]
Made two styles, what one you guys think may be better?

https://i.imgur.com/mF8qFoZ.png
and
https://i.imgur.com/B7gWCy0.png

**Comment by bykidi** [comment]
possible to move?
изображение

**Comment by bykidi** [comment]
If not - second one is better IMO

**Comment by Black4Blade** [comment]
3rd option:
https://i.imgur.com/wiRM5cE.png

Was thinking about it, but I think it's going to be a little too crowded
I see on the default they just had pair unpaid and set pin all on the same level with the enable remote play on the top
Maybe that is an option as well I just dont like the idea with the cheak box on top as much.

Over all can move everything any where

**Comment by Black4Blade** [comment]
4th option:
https://i.imgur.com/Q2qBt4B.png

**Comment by avsaponchik** [comment]
Perfection

**Comment by Black4Blade** [comment]
OK fixed and merged, seem to have some problems with my Git, so using the web upload for now, hopefully, will not create too any issues, I at least can't see any

**Pull request merged**
